### ISSUE TITLE
Маскировка пароля

### ISSUE THREAD

**Issue by zdimon** [zdimon/pressa-besa#34]
При авторизации нет маскировки пароля, виден когда вводишь.

**Comment by Nizhurin** [comment]
![Screenshot_20220220_032220](https://user-images.githubusercontent.com/12280870/154824707-d15fbe07-0552-4cba-a0dc-d79a46e3f1b2.png)
![Screenshot_20220220_032158](https://user-images.githubusercontent.com/12280870/154824708-e0d1c570-3bb4-419b-a765-99acb7715ec9.png)
Дима нужна помощь так как картинка с глазом возле пароля не отображается но если на нее клацать пароль то отображается то скрівается по умолчанию скрівается

**Comment by zdimon** [comment]
@Nizhurin https://github.com/zdimon/pressa-besa/pull/52 сделал
